### ISSUE TITLE
Example of how to encrypt a stream?

### ISSUE THREAD

**Issue by bcomnes** [emilbayes/crypto-stream-xor#1]
Do you have any examples how to use this to encrypt a stream?

**Comment by emilbayes** [comment]
@bcomnes Yes! :) This is a wrapper for the simple `crypto_stream` primitive, which is unauthenticated. `crypto_secretstream` is much better for applications that want a secure channel. I've made a wrapper for that, and am working on porting it to the browser now: https://github.com/emilbayes/secretstream-stream

**Comment by bcomnes** [comment]
Thanks!
